### ISSUE TITLE
Recommendation for sniffing CAN bus data

### ISSUE THREAD

**Issue by Elmue** [SimonRafferty/Polaris-General-2021---CANBUS-Hacking#2]
Hello

I just recommend you a very powerful tool for sniffing CAN bus: HUD ECU Hacker
https://netcult.ch/elmue/hud%20ecu%20hacker/

HUD ECU Hacker can sniff CAN Raw and ISO 15765 data.

You can use a cheap J2534 adapter. A chinese adapter clone costs about $40 US.
You can also use UsbCAN adapters.
HUD ECU Hacker runs on Windows where memory is not a problem.
It has an ultra fast Trace pane where you see CAN Bus traffic in real time.
You can also log CAN bus traffic into an HTML logfile.
And obviously you can set filters for CAN bus IDs.
You can even send packets manually to the CAN bus.
And in the ECU emulator you can write an XML file with automatic responses to specific packets.

**Comment by SimonRafferty** [comment]
If you look more carefully, I'm using a Teensy 4 which has 3 CAN ports built in - and is more than fast enough for the job.

I guess this is really just an advert for your product.  However, it's an OBD2 Scanner with pre-programmed protocol definitions.
The vehicle I used this on was J1939 - which you don't mention at all!  I suspect it would have been useless!

Reading the raw data & just looking for patterns in a protocol independent way is far more powerful.  It doesn't make any difference what ECU or device the data is coming from - it will read it regardless.

You have to do the legwork figuring out what it means - but generally, that's easy.

No generic OBD scanner is going to do as good a job, not even one called the 'ECU Hacker'.

Sorry - but there's no way on earth I would buy your product!

**Comment by Elmue** [comment]
Hello

It is obvious that you did not even visit the page of HUD ECU Hacker nor did you read anything written there.
There is nothing to buy at all.
You can download, install and use it without paying.
I do not earn money with this software.

You are judging without knowing what you are talking about.

It supports many protocols, not only OBD2.
There are no "pre programmed" definitions.
If you would read you would see the EVERYBODY can extend HUD ECU Hacker by adding an XML file for any ECU model!

HUD ECU Hacker can manage also CAN Raw packets and everybody can extend HUD ECU Hacker to scan also your ECU by easily adding an XML file. No problem. 

Additionally there many features like automatically finding the formula for any parameter by using the ECU emulator.
Also you can send packets manually to the ECU.
HUD ECU Hacker has this name because it was made exactly for what you are doing: Hacking ECUs.

**Comment by SimonRafferty** [comment]
Blah blah - not interested.
